tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "aws-iam-authenticator"
cask "1password"
cask "balenaetcher"
cask "bettertouchtool"
cask "caffeine"
cask "clipy"
cask "docker"
cask "google-chrome"
cask "kitty"
cask "monitorcontrol"
cask "pritunl"
cask "slack"
cask "spotify"

tap "homebrew/cask-versions"
cask "google-chrome-canary"

tap "homebrew/cask-drivers"
cask "logitech-options"
