#!/usr/bin/env bash
set -u

tput setaf 1
echo -e '\nUpdating firmware [system]...\033[0m'
sudo fwupdmgr refresh
sudo fwupdmgr update

tput setaf 1
echo -e '\nNixOS Switch [system]...\033[0m'
sudo nixos-rebuild switch

tput setaf 1
echo -e '\nUpdating Home-Manager flake inputs [user]...\033[0m'
cd ~/.config/home-manager || exit 1
nix flake update

tput setaf 1
echo -e '\nHome-Manager Switch [user]...\033[0m'
home-manager switch --flake ~/.config/home-manager#nelson --impure

tput setaf 1
echo -e '\nCRUD secret files [start agenix service]...\033[0m'
systemctl start --user agenix
